FRONTEND/css/outline.css, FRONTEND/html/outline.html
23.05.22 - 김민수 - 프론트 제작용 HTML, CSS
=> 23.05.22 - 김민수 - 프론트 제작용 HTML, CSS

FRONTEND/css/outline.css, FRONTEND/html/outline.html, 테스트 - 복사본.txt
=> 23.05.22 최영탁 최신화

FRONTEND/css/introduce.css, FRONTEND/html/introduce.html
2023.05.23 / DGL / 영화소개 페이지 제작중 / 히히
=> 2023.05.23 / DGL / 영화소개 페이지 제작중 / 히히

FRONTEND/css/managerPage/managerPage.css, FRONTEND/css/managerPage/reset.css, FRONTEND/html/manager/managerPage.html
23.05.24 - 오후 9시 43분 - 김민수 - 판리자 페이지 레이아웃
=> 23.05.24 - 오후 9시 43분 - 김민수 - 판리자 페이지 레이아웃

FRONTEND/css/introduce.css, FRONTEND/html/introduce.html
2023.05.24 / DGL / 생각보다 영화세부가 오래걸리네요 ㅠㅠ 흐엥..
=> 2023.05.24 / DGL / 생각보다 영화세부가 오래걸리네요 ㅠㅠ 흐엥..

FRONTEND/css/introduce.css, FRONTEND/css/playground.css, FRONTEND/css/theater.css, FRONTEND/html/common/footer.html, FRONTEND/html/common/header.html, FRONTEND/html/common/main.html, FRONTEND/html/common/outline.html, FRONTEND/html/introduce/introduce.html, FRONTEND/html/introduce/movielist.html, FRONTEND/html/introduce/playground.html, FRONTEND/html/introduce/theater.html
23.05.25 / DGL / 하.. 넘모힘들어용.. 영화관소개 제작中
=> 23.05.25 / DGL / 하.. 넘모힘들어용.. 영화관소개 제작中

FRONTEND/css/theater.css, FRONTEND/css/theater_s.css, FRONTEND/html/introduce/theater.html, FRONTEND/html/introduce/theater_s.html
=> 23.05.26 / DGL / 영화관메인페이지 /

FRONTEND/css/notice.css, FRONTEND/html/notice.html
=> 23.05.26 최영탁 공지사항

BACKEND/MOVIE/src/main/java/com/kh/kgv/mypage/controller/MyPageController.java, BACKEND/MOVIE/src/main/java/com/kh/kgv/mypage/model/service/MyPageService.java, BACKEND/MOVIE/src/main/java/com/kh/kgv/mypage/model/service/MyPageServiceImpl.java, BACKEND/MOVIE/src/main/webapp/WEB-INF/views/common/header.jsp, BACKEND/MOVIE/src/main/webapp/WEB-INF/views/common/main.jsp, BACKEND/MOVIE/src/main/webapp/WEB-INF/views/myPage/myPage_info.jsp
23.05.29_9:00_ YUN_main들어가는 거하고 mypage가는거 a태그 설정 함
=> 23.05.29_9:00_ YUN_main들어가는 거하고 mypage가는거 a태그 설정 함

BACKEND/MOVIE/src/main/java/com/kh/kgv/mypage/controller/MyPageController.java, BACKEND/MOVIE/src/main/java/com/kh/kgv/mypage/model/service/MyPageService.java, BACKEND/MOVIE/src/main/java/com/kh/kgv/mypage/model/service/MyPageServiceImpl.java, BACKEND/MOVIE/src/main/resources/spring/appServlet/servlet-context.xml, BACKEND/MOVIE/src/main/webapp/WEB-INF/views/common/header.jsp, BACKEND/MOVIE/src/main/webapp/WEB-INF/views/common/main.jsp, BACKEND/MOVIE/src/main/webapp/WEB-INF/views/myPage/myPage_info.jsp
=> 2023.05.29 - 정지민 - full

BACKEND/MOVIE/src/main/java/com/kh/kgv/common/filter/InitFilter.java, BACKEND/MOVIE/src/main/webapp/WEB-INF/views/myPage/myPage_info.jsp, BACKEND/MOVIE/src/main/webapp/WEB-INF/web.xml
=> 23.05.29_21:45_ YUN_필터 수정 중

BACKEND/MOVIE/src/main/java/com/kh/kgv/login/LoginController.java, BACKEND/MOVIE/src/main/webapp/WEB-INF/views/common/header.jsp, BACKEND/MOVIE/src/main/webapp/WEB-INF/views/login/login.jsp, FRONTEND/css/login/loginTest.css, FRONTEND/html/login/loginTest.html, FRONTEND/js/loginpage/loginpage.js
=> 2023.05.30 - 정지민 - 낮이되었습니다

BACKEND/MOVIE/src/main/java/com/kh/kgv/login/controller/SignUpController.java, BACKEND/MOVIE/src/main/java/com/kh/kgv/login/model/dao/SignUpDAO.java, BACKEND/MOVIE/src/main/java/com/kh/kgv/login/model/service/SignUpService.java, BACKEND/MOVIE/src/main/java/com/kh/kgv/login/model/service/SignUpServiceImpl.java, BACKEND/MOVIE/src/main/webapp/WEB-INF/views/common/header.jsp, BACKEND/MOVIE/src/main/webapp/resources/js/signUp/signUp.js
=> 23.05.31 최영탁 최신화

BACKEND/MOVIE/src/main/java/com/kh/kgv/login/controller/SignUpController.java, BACKEND/MOVIE/src/main/java/com/kh/kgv/login/model/dao/SignUpDAO.java, BACKEND/MOVIE/src/main/java/com/kh/kgv/login/model/service/SignUpService.java, BACKEND/MOVIE/src/main/java/com/kh/kgv/login/model/service/SignUpServiceImpl.java, BACKEND/MOVIE/src/main/webapp/WEB-INF/views/signUp/signUp.jsp, BACKEND/MOVIE/src/main/webapp/resources/js/signUp/signUp.js
=> 23.05.31 최영탁 회원가입업데이트

BACKEND/MOVIE/src/main/java/com/kh/kgv/login/controller/LoginController.java, BACKEND/MOVIE/src/main/webapp/WEB-INF/views/login/login.jsp, BACKEND/MOVIE/src/main/webapp/WEB-INF/views/login/login_welcome.jsp, BACKEND/MOVIE/src/main/webapp/resources/css/login/login_welcome.css, BACKEND/MOVIE/src/main/webapp/resources/js/login/login.js, FRONTEND/css/login/login_welcome.css, FRONTEND/html/login/login_welcome.html, FRONTEND/js/loginpage/loginpage.js
=> 2023.05.31 - 정지민 - 휴 힘들다

BACKEND/MOVIE/src/main/java/com/kh/kgv/login/model/dao/SignUpDAO.java, BACKEND/MOVIE/src/main/java/com/kh/kgv/login/model/service/SignUpServiceImpl.java, BACKEND/MOVIE/src/main/webapp/WEB-INF/views/signUp/signUp.jsp, BACKEND/MOVIE/src/main/webapp/resources/js/signUp/signUp.js
=> 23.06.01 최영탁 집에서최신화

BACKEND/MOVIE/src/main/java/com/kh/kgv/management/controller/ManagerController.java
=> 23.06.01 - 관리자 페이지용 컨트롤러 생성

BACKEND/MOVIE/src/main/java/com/kh/kgv/login/controller/LoginController.java
=> 2023.06.01 - 정지민 - 꺼밋

BACKEND/MOVIE/src/main/java/com/kh/kgv/login/controller/SignUpController.java, BACKEND/MOVIE/src/main/java/com/kh/kgv/login/model/dao/SignUpDAO.java, BACKEND/MOVIE/src/main/java/com/kh/kgv/login/model/service/SignUpService.java, BACKEND/MOVIE/src/main/java/com/kh/kgv/login/model/service/SignUpServiceImpl.java, BACKEND/MOVIE/src/main/resources/mappers/user-mapper.xml, BACKEND/MOVIE/src/main/webapp/WEB-INF/views/signUp/signUp.jsp, BACKEND/MOVIE/src/main/webapp/resources/js/signUp/signUp.js
=> 23.06.01 최영탁 브렌치최신화

FRONTEND/js/main/main.js
=> 2023.06.01 / DGL / JS 최신화 ~^^

BACKEND/MOVIE/src/main/java/com/kh/kgv/login/controller/LoginController.java, BACKEND/MOVIE/src/main/webapp/WEB-INF/views/login/login.jsp
=> 23.06.02 - 정지민 - 울랄라세션 개꿀
